### ISSUE TITLE
can't load feed in ttrss

### ISSUE THREAD

**Issue by teodesian** [Troglodyne-Internet-Widgets/tCMS#105]
Couldn't download the specified URL: ; 60 SSL certificate problem: unable to get local issuer certificate

**Comment by teodesian** [comment]
https://stackoverflow.com/questions/24611640/curl-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate

**Comment by troglodyne** [comment]
Outdated packages on the ttrss host. Not our problem. Updating the host myself to fix it
