### ISSUE TITLE
Emoji in posts is broken

### ISSUE THREAD

**Issue by teodesian** [Troglodyne-Internet-Widgets/tCMS#156]
:'(

**Comment by EvanCarroll** [comment]
They're not broken because of tCMS though. I wanted to research this one before I filed it. On Linux the emoji font isn't packaged with Chromium. I have no idea if this works in Google Chrome. But it's easily fixed.

https://unix.stackexchange.com/questions/627257/emoji-do-not-show-up-in-chromijm

**Comment by teodesian** [comment]
I noticed when posting the other day some encoding mangling, I think that is what I was filing on here
